[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 